name: ${name}
version: ${version}
author: ${author}
main: dev.isnow.pluginbase.PluginBase
api-version: '1.21'
softdepend:
  - PlaceholderAPI
  - packetevents
  - Vault
libraries:
  - org.hibernate:hibernate-core:6.2.8.Final
  - jakarta.validation:jakarta.validation-api:3.0.2
  - jakarta.persistence:jakarta.persistence-api:3.1.0
  - org.mariadb.jdbc:mariadb-java-client:3.3.3
  #  - org.hibernate.validator:hibernate-validator:8.0.0.Final
  - com.h2database:h2:2.2.224
  - com.mysql:mysql-connector-j:9.0.0
  - de.exlll:configlib-paper:4.6.1
  - com.github.ben-manes.caffeine:caffeine:3.2.2
  - com.github.ben-manes.caffeine:jcache:3.2.2
  - org.hibernate:hibernate-jcache:6.2.8.Final
#  - studio.mevera:imperat-core:1.9.7
#  - studio.mevera:imperat-bukkit:1.9.7